### ISSUE TITLE
Problem with clearing the cache in TYPO3 8.7.16

### ISSUE THREAD

**Issue by adriamar** [xperseguers/t3ext-cloudflare#2]
After activating the plugin, there is no icon responsible for clearing the cloudflare cache in the TYPO3 backend (something is trying to load but with no results) and error messages appear when flushing the standard TYPO3 cache. When the cloudflare extension is deactivated, everything works fine.

**Comment by xperseguers** [comment]
Please confirm that everything's fine now. Thx

**Comment by adriamar** [comment]
Everything works fine now. Thanks for the help :)
