### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by lavitto-private** [xperseguers/t3ext-cloudflare#29]
Is an update for TYPO3 12 planned?

**Comment by georgringer** [comment]
just wanted to ask as well. thanks for your previous work!

**Comment by doreinhardt** [comment]
Is there any new information regarding the v12 compatibility or any ETA when there will be a release?
Thanks for the work :)

**Comment by xperseguers** [comment]
Please use latest release.
