### ISSUE TITLE
Selected domains are not saved in extension configuration

### ISSUE THREAD

**Issue by jacobsenj** [xperseguers/t3ext-cloudflare#30]
TYPO3: 12.4.20
PHP: 8.1.29

![Bildschirmfoto 2024-10-23 um 12 47 07](https://github.com/user-attachments/assets/b598b7ad-f55a-4657-af3f-b4bd3bb53d6b)

Currently the selected domains will not get saved into `config/system/settings.php`. The array key will stay empty. Setting the domains only works when entering `<identifier>|<zone>` manually into the file. It will get overwritten to `empty` when saving the extension configuration afterwards again:

![Bildschirmfoto 2024-10-23 um 12 49 19](https://github.com/user-attachments/assets/c7d0aeef-758c-40e0-af02-93c0480450f5)

**Comment by xperseguers** [comment]
Did you check the console to see if you happen to get JS errors?

**Comment by xperseguers** [comment]
@jacobsenj Could you check that the proposed PR #31 fixes this issue? Thanks for dropping some comment :)

**Comment by mmalisz** [comment]
> @jacobsenj Could you check that the proposed PR #31 fixes this issue? Thanks for dropping some comment :)

Hi,
it seems that this patch works for v12 - the selected domain was added to `settings.php` file.

Not sure how this worked previously, but after that patch, instead of `'domains' => ''` key, two new ones were added:
`'domains_0' -> 'id|domain.com'` and `'domains_count' => '1'` - not sure if that is desired 

Tested on 12.4.23.

**Comment by xperseguers** [comment]
Hi @mmalisz, thanks for testing and reporting. The change in `'domains' => ''` to `'domain_0' => ...` is intended, I found no other way to make it work with all the JS-related restrictions we now have in the Install Tool / Extension settings. I thus had to rely on pure `form` values and work with an array of virtual fields instead.

**Comment by mmalisz** [comment]
@xperseguers,
is there going to be a release soon?

Right now I've created a composer patch, but I don't know if should deploy my project that way if a new version will be available soon.

**Comment by xperseguers** [comment]
There will certainly be a release soon. You could temporarily switch to `dev-master` as well instead of configuring a composer patch.

**Comment by mmalisz** [comment]
Great, thanks.

**Comment by mmalisz** [comment]
@xperseguers,
found one issue - not sure if it matters, though.

If I uncheck the domain, the `domain_X` key gets removed, but the `domains_count` remains intact.

**Comment by xperseguers** [comment]
that's "intended" :) please report if you find that it leads to some problems (it shouldn't, I'm aware of this behaviour), otherwise, just be happy that it works fine :)

**Comment by kvonspiczak-sgalinski** [comment]
any chance for a release on this bugfix in the 2.x branch? just stumbled upon this issue, while setting up this extension for a customer.
