### ISSUE TITLE
PHP 7.3 compatibility in composer.json and ext_emconf.php

### ISSUE THREAD

**Issue by lavitto-private** [xperseguers/t3ext-cloudflare#6]
I use your extension in some 9.5 installations with PHP 7.3 and everything works fine. I think you can add PHP 7.3 compatibility to your composer.json and ext_emconf.php. Otherwise we have to add --ignore-platform-reqs to every composer installation with the cloudflare-extension.

**Comment by xperseguers** [comment]
This is already the case in master branch since 16.04.2019
